# Generated by Django 2.2.20 on 2021-05-16 18:54

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0115_enterpriseanalyticsuser_historicalenterpriseanalyticsuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('course_metadata', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict})),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(max_length=20)),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default='active', max_length=10)),
                ('license_count', models.IntegerField(default=1)),
                ('biller_subscription_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ecommerce_transaction_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default='active', max_length=10)),
                ('license_count', models.IntegerField()),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('biller_invoice_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ecommerce_trans_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_id', models.IntegerField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('billing_cycle_options', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict})),
                ('grace_period', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Bundle')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
