# Generated by Django 2.2.20 on 2021-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bundle_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('billing_cycle_options', models.CharField(max_length=50)),
                ('grace_period', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
