# Generated by Django 2.2.20 on 2021-05-17 09:51

from django.db import migrations, models
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='course_metadata',
        ),
        migrations.AddField(
            model_name='bundle',
            name='courses',
            field=models.ManyToManyField(to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10),
        ),
    ]
