# Generated by Django 2.2.20 on 2021-05-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='billing_cycle_options',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='one_time_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='ecommerce_prod_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ecommerce Product ID'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_prod_id',
            field=models.CharField(max_length=50, verbose_name='Stripe Product ID'),
        ),
    ]
