# Generated by Django 2.2.20 on 2021-05-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210519_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='monthly_price',
            new_name='price_month',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='one_time_price',
            new_name='price_onetime',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='yearly_price',
            new_name='price_year',
        ),
    ]
