# Generated by Django 2.2.20 on 2021-05-17 12:35

import collections
from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210517_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='ecommerce_transaction_id',
            new_name='ecommerce_trans_id',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='product_id',
            new_name='ecommerce_prod_id',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle_options',
            field=jsonfield.fields.JSONField(blank=True, default=[{'monthly': '0.00', 'yearly': '0.00'}], dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='grace_period',
            field=models.IntegerField(default=0),
        ),
    ]
