# Generated by Django 2.2.20 on 2021-05-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210517_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.Bundle'),
        ),
    ]
