# Generated by Django 2.2.20 on 2021-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210520_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_month_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe Price ID (month)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_year_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe Product ID (year)'),
        ),
    ]
