# Generated by Django 2.2.20 on 2021-05-17 14:03

from django.db import migrations, models
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210517_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[(lms.djangoapps.subscriptions.models.BillingCycles('monthly'), 'monthly'), (lms.djangoapps.subscriptions.models.BillingCycles('yearly'), 'yearly'), (lms.djangoapps.subscriptions.models.BillingCycles('one-time'), 'one-time')], default=lms.djangoapps.subscriptions.models.BillingCycles('monthly'), max_length=10),
        ),
    ]
