# Generated by Django 2.2.20 on 2021-05-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0115_enterpriseanalyticsuser_historicalenterpriseanalyticsuser'),
        ('subscriptions', '0005_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer'),
        ),
    ]
