# Generated by Django 2.2.20 on 2021-05-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210520_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='biller_subscription_id',
            new_name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_utap_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
