# Generated by Django 2.2.20 on 2021-05-25 06:03

from django.db import migrations, models
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20210525_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('month', 'MONTH'), ('year', 'YEAR'), ('one-time', 'ONE_TIME')], default=lms.djangoapps.subscriptions.models.BillingCycles('month'), max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
