# Generated by Django 2.2.20 on 2021-05-27 05:33

from django.db import migrations, models
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20210525_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_at',
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.CharField(blank=True, choices=[('CREATED', 'CREATE'), ('RENEWAL', 'RENEW'), ('CANCELLED', 'CANCEL'), ('EXPIRED', 'EXPIRE')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], default=lms.djangoapps.subscriptions.models.Statuses('active'), max_length=10),
        ),
    ]
