# Generated by Django 2.2.20 on 2021-05-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20210510_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.EnterpriseCustomer'),
        ),
    ]
