# Generated by Django 2.2.20 on 2021-05-10 08:31

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0115_enterpriseanalyticsuser_historicalenterpriseanalyticsuser'),
        ('subscriptions', '0008_auto_20210510_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='license',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='license',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='bundle_id',
        ),
        migrations.AddField(
            model_name='license',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription'),
        ),
        migrations.AddField(
            model_name='license',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseCustomer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Bundle'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle_options',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
