# Generated by Django 2.2.20 on 2021-05-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210527_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='status',
        ),
    ]
