# Generated by Django 2.2.20 on 2021-05-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20210510_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_enterprise',
        ),
    ]
