# Generated by Django 2.2.20 on 2021-05-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20210527_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='biller_invoice_id',
            new_name='stripe_invoice_id',
        ),
    ]
