# Generated by Django 2.2.20 on 2021-05-16 06:57

from django.db import migrations, models
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_remove_subscription_is_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='biller_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ecommerce_transaction_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default='active', max_length=10),
        ),
    ]
