# Generated by Django 2.2.20 on 2021-05-16 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lms.djangoapps.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_auto_20210516_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='biller_invoice_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ecommerce_trans_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='license_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[(lms.djangoapps.subscriptions.models.Statuses('active'), 'active'), (lms.djangoapps.subscriptions.models.Statuses('inactive'), 'inactive'), (lms.djangoapps.subscriptions.models.Statuses('expired'), 'expired'), (lms.djangoapps.subscriptions.models.Statuses('cancelled'), 'cancelled')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='subscription',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ecommerce_transaction_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='license_count',
            field=models.IntegerField(default=1),
        ),
    ]
